name: Run Python E2E tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'lab/**'
      - 'assets/**'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'lab/**'
      - 'assets/**'

jobs:
  test_package:

    name: Test ${{ matrix.os }} Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    services:
      db:
        image: mysql:8.2
        env:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_DATABASE: relecloud
        ports:
        - 3306:3306
        # needed because the mysql container does not provide a healthcheck
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
        - uses: actions/checkout@v4
        - name: Setup python
          uses: actions/setup-python@v2
          with:

            python-version: ${{ matrix.python_version }}
            architecture: x64
        - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements-dev.txt
            playwright install chromium --with-deps
            python3 -m pip install -e src
        - name: Seed data and run Pytest tests
          run: |
            python3 -m flask --app src.flaskapp db upgrade --directory src/flaskapp/migrations
            python3 -m flask --app src.flaskapp seed --filename src/seed_data.json
            python3 -m pytest
          env:
            MYSQL_HOST: localhost
            MYSQL_USER: root
            MYSQL_PASS: mysql
            MYSQL_DATABASE: relecloud